{'seed': 0, 'dataset_name': 'covid', 'do_train': True, 'load_model': '/home/s5srinivasan/covid-annotation-scgpt/save/scgpt-human', 'mask_ratio': 0.0, 'epochs': 10, 'n_bins': 51, 'MVC': False, 'ecs_thres': 0.0, 'dab_weight': 0.0, 'lr': 0.0001, 'batch_size': 18, 'layer_size': 128, 'nlayers': 4, 'nhead': 4, 'dropout': 0.2, 'schedule_ratio': 0.9, 'save_eval_interval': 5, 'fast_transformer': True, 'pre_norm': False, 'amp': True, 'include_zero_gene': False, 'freeze': False, 'DSBN': False}
save to /home/s5srinivasan/covid-annotation-scgpt/save/dev_covid-Feb21-16-04
Traceback (most recent call last):
  File "/home/s5srinivasan/covid-annotation-scgpt/code/finetuning/02_prediction_finetuning_on_Nikolic.py", line 255, in <module>
    countsOriginal = adataOriginal.obs.annotation_detailed.value_counts()
NameError: name 'adataOriginal' is not defined
Traceback (most recent call last):
  File "/home/s5srinivasan/covid-annotation-scgpt/code/finetuning/02_prediction_finetuning_on_Nikolic.py", line 255, in <module>
    countsOriginal = adataOriginal.obs.annotation_detailed.value_counts()
NameError: name 'adataOriginal' is not defined
